import { randomRGBAGenerator } from "./utils";
import {
  CartoliciousFill,
  CartoliciousStroke,
  CartoliciousStyle,
} from "../interfaces";

const emptyStyle: CartoliciousStyle = [[], [], 0];

const defaultCartoliciousStyle: CartoliciousStyle = [
  [255, 255, 255, 1, 1],
  [255, 255, 255, 1, 0, 1],
  1,
];

export const mapboxAttributes: Set<string> = new Set([
  "admin",
  "runway",
  "taxiway",
  "apron",
  "helipad",
  "landuse",
  "building",
  "national_park",
  "wetland",
  "wetland_noveg",
  "aboriginal_lands",
  "agriculture",
  "airport",
  "cemetery",
  "glacier",
  "grass",
  "hospital",
  "park",
  "parking",
  "piste",
  "pitch",
  "rock",
  "sand",
  "school",
  "scrub",
  "wood",
  "facility",
  "motorway",
  "motorway_link",
  "trunk",
  "trunk_link",
  "primary",
  "primary_link",
  "secondary",
  "secondary_link",
  "tertiary",
  "tertiary_link",
  "street",
  "street_limited",
  "pedestrian",
  "construction",
  "track",
  "service",
  "ferry",
  "path",
  "major_rail",
  "minor_rail",
  "service_rail",
  "aerialway",
  "golf",
  "roundabout",
  "mini_roundabout",
  "turning_circle",
  "turning_loop",
  "traffic_signals",
  "cliff",
  "fence",
  "gate",
  "hedge",
  "land",
  "water",
  "river",
  "canal",
  "stream",
  "drain",
  "ditch",
  "apartments",
  "civil",
  "residential",
  "settlement",
  "settlement_subdivision",
  "arts_and_entertainment",
  "education",
  "general",
  "park_like",
  "medical",
  "historic",
  "public_facilities",
  "transit_stop_label",
  "religion",
  "lodging",
  "military",
  "industrial",
  // "housenum_label",
  "level_crossing",
  "motorist",
  "food_and_drink_stores",
  "food_and_drink",
  "terrace",
  "place_like",
  "commercial",
  "sport_and_leisure",
  "garages",
  "church",
  "store_like",
  "commercial_services",
  "garage",
  "retail",
  "farm",
  "hotel",
  "house",
  "detached",
  "residential",
  "dormitory",
  "terrace",
  "houseboat",
  "bungalow",
  "cabin",
  "commercial",
  "office",
  "industrial",
  "retail",
  "supermarket",
  "warehouse",
  "kiosk",
  "religious",
  "cathedral",
  "temple",
  "chapel",
  "church",
  "mosque",
  "synagogue",
  "shrine",
  "civic",
  "government",
  "hospital",
  "school",
  "transportation",
  "stadium",
  "train_station",
  "university",
  "grandstand",
  "public",
  "barn",
  "bridge",
  "bunker",
  "carport",
  "conservatory",
  "construction",
  "garage",
  "garages",
  "farm_auxiliary",
  "garbage_shed",
  "greenhouse",
  "hangar",
  "hut",
  "pavilion",
  "parking",
  "roof",
  "sports_hall",
  "shed",
  "stable",
  "service",
  "ruins",
  "transformer_tower",
  "water_tower",
  "waterway",
  "stream_intermittent",
  "visitor_amenities",
  "kindergarten",
  "toilets",
  "building:part",
  "pumping_station",
  "data_center",
  "housenum_label",
  "landform",
  "terminal",
  "reservoir",
  "bay",
  "state",
]);

export const generateEmptyCartoliciousStyles = (): Map<
  string,
  CartoliciousStyle
> => {
  const newStyleMap = new Map().set("default", emptyStyle);

  mapboxAttributes.forEach((attribute) => {
    newStyleMap.set(attribute, emptyStyle);
  });

  return newStyleMap;
};

export const generateRandomCartoliciousStyles = (): Map<
  string,
  CartoliciousStyle
> => {
  const newStyleMap = new Map().set("default", defaultCartoliciousStyle);

  mapboxAttributes.forEach((attribute) => {
    const newCartoliciousStyle: CartoliciousStyle = [
      [...randomRGBAGenerator(), 1],
      [...randomRGBAGenerator(), 1, 1],
      1,
    ];

    newStyleMap.set(attribute, newCartoliciousStyle);
  });

  return newStyleMap;
};
